# Generated by Django 4.1.5 on 2024-02-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("padron", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="RptVisita", new_name="Padron",),
    ]
