# Generated by Django 4.1.5 on 2024-02-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron", "0004_padron_cod_microred_padron_cod_red_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="padron",
            name="edad_0_28_dias",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_0_5_meses",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_1_anio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_2_anios",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_3_anios",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_4_anios",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_5_anios",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_6_11_meses",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_anio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_dias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="edad_mes_actual",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="menores_de_12_meses",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
