# Generated by Django 4.1.5 on 2024-02-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron", "0005_padron_edad_0_28_dias_padron_edad_0_5_meses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="padron",
            name="Apellido_Materno_Personal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="Apellido_Paterno_Personal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="padron",
            name="Nombres_Personal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
