# Generated by Django 4.1.5 on 2024-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron", "0006_padron_apellido_materno_personal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_padron", models.CharField(blank=True, max_length=50, null=True)),
                ("cnv", models.CharField(blank=True, max_length=50, null=True)),
                ("cui", models.CharField(blank=True, max_length=50, null=True)),
                ("dni", models.CharField(blank=True, max_length=50, null=True)),
                ("ubigeo", models.CharField(blank=True, max_length=50, null=True)),
                ("num_doc", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_nac", models.CharField(blank=True, max_length=50, null=True)),
                ("edad_anio", models.CharField(blank=True, max_length=50, null=True)),
                ("edad_mes", models.CharField(blank=True, max_length=50, null=True)),
                ("edad_dias", models.CharField(blank=True, max_length=50, null=True)),
                ("seguro", models.CharField(blank=True, max_length=50, null=True)),
                ("ap_paterno", models.CharField(blank=True, max_length=50, null=True)),
                ("ap_materno", models.CharField(blank=True, max_length=50, null=True)),
                ("nom_nino", models.CharField(blank=True, max_length=50, null=True)),
                ("direccion", models.CharField(blank=True, max_length=250, null=True)),
                ("eje", models.CharField(blank=True, max_length=50, null=True)),
                ("referencia", models.CharField(blank=True, max_length=250, null=True)),
                ("provincia", models.CharField(blank=True, max_length=250, null=True)),
                ("distrito", models.CharField(blank=True, max_length=250, null=True)),
                ("area", models.CharField(blank=True, max_length=50, null=True)),
                ("visitado", models.CharField(blank=True, max_length=50, null=True)),
                ("fe_visita", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cod_eess_padron",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nom_eess_padron",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("frecuencia", models.CharField(blank=True, max_length=50, null=True)),
                ("encontrado", models.CharField(blank=True, max_length=50, null=True)),
                ("dni_mama", models.CharField(blank=True, max_length=50, null=True)),
                ("num_cel", models.CharField(blank=True, max_length=50, null=True)),
                ("pn_reg", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "edad_mes_actual",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("den", models.IntegerField(blank=True, null=True)),
                ("num", models.IntegerField(blank=True, null=True)),
                ("edad_0_28_dias", models.IntegerField(blank=True, null=True)),
                ("edad_0_5_meses", models.IntegerField(blank=True, null=True)),
                ("edad_6_11_meses", models.IntegerField(blank=True, null=True)),
                ("menores_de_12_meses", models.IntegerField(blank=True, null=True)),
                ("edad_1_anio", models.IntegerField(blank=True, null=True)),
                ("num_num_doc", models.IntegerField(blank=True, null=True)),
                ("num_eje", models.IntegerField(blank=True, null=True)),
                ("num_ref", models.IntegerField(blank=True, null=True)),
                ("num_vis", models.IntegerField(blank=True, null=True)),
                ("num_enc", models.IntegerField(blank=True, null=True)),
                ("num_seguro", models.IntegerField(blank=True, null=True)),
                ("num_nom_eess_padron", models.IntegerField(blank=True, null=True)),
                ("num_num_cel", models.IntegerField(blank=True, null=True)),
                ("num_frecuencia", models.IntegerField(blank=True, null=True)),
                ("num_entidad_eess", models.IntegerField(blank=True, null=True)),
                ("num_entidad_muni", models.IntegerField(blank=True, null=True)),
                ("num_entidad_reniec", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
