# Generated by Django 4.1.5 on 2024-02-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActualizaBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_plano",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hora_plano", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fecha_paciente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_paciente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fecha_personal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_personal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fecha_padron",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_padron",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fecha_certificado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_certificado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Directorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diresa", models.CharField(blank=True, max_length=100, null=True)),
                ("red", models.CharField(blank=True, max_length=100, null=True)),
                ("microred", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "establecimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diresa", "diresa"),
                            ("red", "red"),
                            ("microred", "microred"),
                            ("establecimiento", "establecimiento"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "perfil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Consultor", "Consultor"),
                            ("Registrador", "Registrador"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Alta", "Alta"), ("Baja", "Baja")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cuenta_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Si", "Si"),
                            ("No", "No"),
                            ("Espera respuesta MINSA", "Espera respuesta MINSA"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contraseña_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_formato",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/formato/"
                    ),
                ),
                (
                    "dateTimeOfUpload_req_formato",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "req_generales_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/excel/"
                    ),
                ),
                (
                    "dateTimeOfUpload_generales_excel",
                    models.DateTimeField(auto_now=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectorioEstablecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diresa", models.CharField(blank=True, max_length=100, null=True)),
                ("red", models.CharField(blank=True, max_length=100, null=True)),
                ("microred", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "establecimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diresa", "diresa"),
                            ("red", "red"),
                            ("microred", "microred"),
                            ("establecimiento", "establecimiento"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "perfil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Consultor", "Consultor"),
                            ("Registrador", "Registrador"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Alta", "Alta"), ("Baja", "Baja")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cuenta_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Si", "Si"),
                            ("No", "No"),
                            ("Espera respuesta MINSA", "Espera respuesta MINSA"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contraseña_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_formato",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/formato/"
                    ),
                ),
                (
                    "dateTimeOfUpload_req_formato",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "req_generales_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/excel/"
                    ),
                ),
                (
                    "dateTimeOfUpload_generales_excel",
                    models.DateTimeField(auto_now=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectorioRed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diresa", models.CharField(blank=True, max_length=100, null=True)),
                ("red", models.CharField(blank=True, max_length=100, null=True)),
                ("microred", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "establecimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diresa", "diresa"),
                            ("red", "red"),
                            ("microred", "microred"),
                            ("establecimiento", "establecimiento"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "perfil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Consultor", "Consultor"),
                            ("Registrador", "Registrador"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Alta", "Alta"), ("Baja", "Baja")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cuenta_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Si", "Si"),
                            ("No", "No"),
                            ("Espera respuesta MINSA", "Espera respuesta MINSA"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contraseña_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_formato",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/formato/"
                    ),
                ),
                (
                    "dateTimeOfUpload_req_formato",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "req_generales_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/excel/"
                    ),
                ),
                (
                    "dateTimeOfUpload_generales_excel",
                    models.DateTimeField(auto_now=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_diresa",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_diresa",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_distrito",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubigeo_dis", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cod_provincia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_establecimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "codigo_unico",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_microred",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filiacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provincia", models.CharField(blank=True, max_length=100, null=True)),
                ("distrito", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tipo_municipalidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Provincial", "Provincial"),
                            ("Distrital", "Distrital"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "perfil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Consultor", "Consultor"),
                            ("Registrador", "Registrador"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Alta", "Alta"), ("Baja", "Baja")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cuenta_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Si", "Si"),
                            ("No", "No"),
                            ("Espera respuesta MINSA", "Espera respuesta MINSA"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contraseña_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_formato",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/formato/"
                    ),
                ),
                (
                    "dateTimeOfUpload_req_formato",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "req_generales_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/excel/"
                    ),
                ),
                (
                    "dateTimeOfUpload_generales_excel",
                    models.DateTimeField(auto_now=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Microred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_microred",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cod_microred",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_provincia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubigeo", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Red",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_red",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="rpt_certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Anio", models.CharField(blank=True, max_length=200, null=True)),
                ("Mes", models.CharField(blank=True, max_length=200, null=True)),
                ("Dia", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Fecha_Atencion",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                ("Codigo_Red", models.CharField(blank=True, max_length=200, null=True)),
                ("Red", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Codigo_MicroRed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("MicroRed", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Codigo_Unico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Nombre_Establecimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Id_Establecimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("DIS_EVALUACION", models.IntegerField(blank=True, null=True)),
                ("DIS_CALIFICACION", models.IntegerField(blank=True, null=True)),
                ("DIS_LEV", models.IntegerField(blank=True, null=True)),
                ("DIS_MOD", models.IntegerField(blank=True, null=True)),
                ("DIS_SEV", models.IntegerField(blank=True, null=True)),
                ("DIS_TOTAL", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RptSeguimientoVisitaDis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Codigo_Red", models.CharField(blank=True, max_length=200, null=True)),
                ("Red", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Codigo_MicroRed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("MicroRed", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Codigo_Unico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Nombre_Establecimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Id_Establecimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Numero_Documento_Paciente",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "FECHA_VISITA_1",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                (
                    "EESS_VISITA_1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "FECHA_VISITA_2",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                (
                    "EESS_VISITA_2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "FECHA_VISITA_3",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                (
                    "EESS_VISITA_3",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "FECHA_VISITA_4",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                (
                    "EESS_VISITA_4",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RptVisitaDis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Anio", models.CharField(blank=True, max_length=200, null=True)),
                ("Mes", models.CharField(blank=True, max_length=200, null=True)),
                ("Dia", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Fecha_Atencion",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                ("Codigo_Red", models.CharField(blank=True, max_length=200, null=True)),
                ("Red", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Codigo_MicroRed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("MicroRed", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Codigo_Unico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Nombre_Establecimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Id_Establecimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("VISITA_1", models.IntegerField(blank=True, null=True)),
                ("VISITA_2", models.IntegerField(blank=True, null=True)),
                ("VISITA_3", models.IntegerField(blank=True, null=True)),
                ("VISITA_4", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitas", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
