# Generated by Django 4.1.5 on 2024-02-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="establecimiento",
            name="red_microred",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="microred",
            name="red_microred",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
