# Generated by Django 3.2.13 on 2024-02-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiacion', '0002_establecimiento_red_microred_microred_red_microred'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo', models.CharField(blank=True, max_length=50, null=True)),
                ('edad_mes', models.CharField(blank=True, max_length=50, null=True)),
                ('año', models.CharField(blank=True, max_length=50, null=True)),
                ('mes', models.CharField(blank=True, max_length=50, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nac', models.CharField(blank=True, max_length=50, null=True)),
                ('seguro', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_nino', models.CharField(blank=True, max_length=50, null=True)),
                ('visitado', models.CharField(blank=True, max_length=50, null=True)),
                ('encontrado', models.CharField(blank=True, max_length=50, null=True)),
                ('dni_mama', models.CharField(blank=True, max_length=50, null=True)),
                ('num_cel', models.CharField(blank=True, max_length=50, null=True)),
                ('pn_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('Id_Establecimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('den', models.CharField(blank=True, max_length=50, null=True)),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
                ('renaes1', models.CharField(blank=True, max_length=50, null=True)),
                ('renaes2', models.CharField(blank=True, max_length=50, null=True)),
                ('renaes3', models.CharField(blank=True, max_length=50, null=True)),
                ('renaes4', models.CharField(blank=True, max_length=50, null=True)),
                ('visit1', models.CharField(blank=True, max_length=50, null=True)),
                ('visita2', models.CharField(blank=True, max_length=50, null=True)),
                ('visita3', models.CharField(blank=True, max_length=50, null=True)),
                ('visita4', models.CharField(blank=True, max_length=50, null=True)),
                ('Codigo_Departamento_Inei', models.CharField(blank=True, max_length=50, null=True)),
                ('Departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('Codigo_Distrito_Inei', models.CharField(blank=True, max_length=50, null=True)),
                ('Distrito', models.CharField(blank=True, max_length=50, null=True)),
                ('Codigo_Red', models.CharField(blank=True, max_length=50, null=True)),
                ('RED', models.CharField(blank=True, max_length=50, null=True)),
                ('Codigo_MicroRed', models.CharField(blank=True, max_length=50, null=True)),
                ('MicroRed', models.CharField(blank=True, max_length=50, null=True)),
                ('Codigo_Unico', models.CharField(blank=True, max_length=50, null=True)),
                ('Nombre_Establecimiento', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
