# Generated by Django 4.1.5 on 2023-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0003_directorioestablecimiento_directoriored"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitas", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
