# Generated by Django 3.2.13 on 2024-02-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiacion', '0003_rptvisita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rptvisita',
            old_name='Codigo_Departamento_Inei',
            new_name='Codigo_Provincia_Inei',
        ),
        migrations.RenameField(
            model_name='rptvisita',
            old_name='Departamento',
            new_name='Provincia',
        ),
    ]
