# Generated by Django 3.2.13 on 2024-02-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiacion', '0004_auto_20240212_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Item_mes',
        ),
    ]
