# Generated by Django 4.1.5 on 2023-11-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0005_rpt_certificado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rpt_certificado",
            name="Fecha_Atencion",
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
