# Generated by Django 3.2.13 on 2024-02-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiacion', '0005_rename_item_item_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rptvisita',
            old_name='RED',
            new_name='Red',
        ),
    ]
