# Generated by Django 4.1.5 on 2023-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0007_actualizabd"),
    ]

    operations = [
        migrations.CreateModel(
            name="RptVisita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Anio", models.CharField(blank=True, max_length=200, null=True)),
                ("Mes", models.CharField(blank=True, max_length=200, null=True)),
                ("Dia", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Fecha_Atencion",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                ("Codigo_Red", models.CharField(blank=True, max_length=200, null=True)),
                ("Red", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Codigo_MicroRed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("MicroRed", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Codigo_Unico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Nombre_Establecimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Id_Establecimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("VISITA_1", models.IntegerField(blank=True, null=True)),
                ("VISITA_2", models.IntegerField(blank=True, null=True)),
                ("VISITA_3", models.IntegerField(blank=True, null=True)),
                ("VISITA_4", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
