# Generated by Django 3.2.13 on 2024-02-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiacion', '0007_auto_20240212_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rptvisita',
            name='visit1',
        ),
        migrations.AddField(
            model_name='rptvisita',
            name='visita1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rptvisita',
            name='visita2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rptvisita',
            name='visita3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rptvisita',
            name='visita4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
