# Generated by Django 4.1.5 on 2023-11-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0008_rptvisita"),
    ]

    operations = [
        migrations.RenameModel(old_name="RptVisita", new_name="RptVisitaDis",),
    ]
