# Generated by Django 4.1.5 on 2024-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0008_auto_20240212_2148"),
    ]

    operations = [
        migrations.AddField(
            model_name="rptvisita",
            name="direccion",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="rptvisita",
            name="v_fecha1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rptvisita",
            name="v_fecha2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rptvisita",
            name="v_fecha3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rptvisita",
            name="v_fecha4",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
