# Generated by Django 4.1.5 on 2023-11-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0010_rptseguimientovisitadis"),
    ]

    operations = [
        migrations.RemoveField(model_name="rptseguimientovisitadis", name="Anio",),
        migrations.RemoveField(model_name="rptseguimientovisitadis", name="Dia",),
        migrations.RemoveField(
            model_name="rptseguimientovisitadis", name="Fecha_Atencion",
        ),
        migrations.RemoveField(model_name="rptseguimientovisitadis", name="Mes",),
    ]
