# Generated by Django 4.1.5 on 2023-12-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0011_remove_rptseguimientovisitadis_anio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_reporte",
                    models.CharField(
                        choices=[
                            ("D", "Diresa"),
                            ("R", "Red"),
                            ("M", "MicroRed"),
                            ("E", "Establecimiento"),
                        ],
                        max_length=1,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
    ]
