# Generated by Django 4.1.5 on 2023-12-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0012_reporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_diresa",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_diresa",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="Reporte",),
    ]
