# Generated by Django 4.1.5 on 2023-12-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0013_diresa_tiporeporte_delete_reporte"),
    ]

    operations = [
        migrations.RemoveField(model_name="distrito", name="provincia",),
        migrations.RemoveField(model_name="establecimiento", name="microred",),
        migrations.RemoveField(model_name="establecimiento", name="red",),
        migrations.RemoveField(model_name="microred", name="red",),
        migrations.AddField(
            model_name="establecimiento",
            name="cod_microred",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="establecimiento",
            name="cod_red",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
